name: Epi-Guard Microservices CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker-images:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests -f api-gateway/pom.xml
          mvn clean package -DskipTests -f auth-service/pom.xml
          mvn clean package -DskipTests -f patient-service/pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API Gateway
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/epi-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/epi-gateway:latest

      - name: Build and Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/epi-auth:latest ./auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/epi-auth:latest

      - name: Build and Push Patient Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/epi-patient:latest ./patient-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/epi-patient:latest

  deploy-to-kamatera:
    name: Deploy to Kubernetes
    needs: build-and-push-docker-images
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy K8s Blueprint to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "infrastructure.yaml"
          target: "~/epiguard-k8s/"
          overwrite: true

      - name: Trigger Kubernetes Rolling Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Successfully connected to Kamatera!"
            
            # Apply any changes you made to the YAML file automatically
            kubectl apply -f ~/epiguard-k8s/infrastructure.yaml
            
            # Restart the pods using the EXACT names from your infrastructure.yaml
            kubectl rollout restart deployment api-gateway
            kubectl rollout restart deployment auth-service
            kubectl rollout restart deployment patient-service
            
            echo "Deployment successful! The new code is now live."